package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"

	"github.com/guacsec/guac/pkg/assembler/graphql/generated"
	"github.com/guacsec/guac/pkg/assembler/graphql/model"
)

// IngestArtifact is the resolver for the ingestArtifact field.
func (r *mutationResolver) IngestArtifact(ctx context.Context, artifact *model.IDorArtifactInput) (string, error) {
	return r.Backend.IngestArtifact(ctx, artifact)
}

// IngestArtifacts is the resolver for the ingestArtifacts field.
func (r *mutationResolver) IngestArtifacts(ctx context.Context, artifacts []*model.IDorArtifactInput) ([]string, error) {
	return r.Backend.IngestArtifacts(ctx, artifacts)
}

// Artifacts is the resolver for the artifacts field.
func (r *queryResolver) Artifacts(ctx context.Context, artifactSpec model.ArtifactSpec) ([]*model.Artifact, error) {
	return r.Backend.Artifacts(ctx, &artifactSpec)
}

// ArtifactsList is the resolver for the artifactsList field.
func (r *queryResolver) ArtifactsList(ctx context.Context, artifactSpec model.ArtifactSpec, after *string, first *int, before *string, last *int) (*model.ArtifactConnection, error) {
	panic(fmt.Errorf("not implemented: ArtifactsList - artifactsList"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) ArtifactsOrdered(ctx context.Context, artifactSpec model.ArtifactSpec, after *string, first *int, before *string, last *int) (*model.ArtifactConnection, error) {
	panic(fmt.Errorf("not implemented: ArtifactsOrdered - artifactsOrdered"))
}
