package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"
	"fmt"

	"github.com/guacsec/guac/pkg/assembler/graphql/model"
)

// IngestPackage is the resolver for the ingestPackage field.
func (r *mutationResolver) IngestPackage(ctx context.Context, pkg *model.PkgInputSpec) (*model.Package, error) {
	return r.Backend.IngestPackage(ctx, pkg)
}

// Packages is the resolver for the packages field.
func (r *queryResolver) Packages(ctx context.Context, pkgSpec *model.PkgSpec) ([]*model.Package, error) {
	return r.Backend.Packages(ctx, pkgSpec)
}

// PackagesRequiringCertifyVulnerability is the resolver for the packagesRequiringCertifyVulnerability field.
func (r *queryResolver) PackagesRequiringCertifyVulnerability(ctx context.Context, vulnSpec *model.CertifyVulnSpec) ([]*model.Package, error) {
	panic(fmt.Errorf("not implemented: PackagesRequiringCertifyVulnerability - packagesRequiringCertifyVulnerability"))
}
